server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
  rabbitmq:
    host: 192.168.145.136  
eureka:
  instance:
    prefer-ip-address: true
    instance-id: tensquare-base
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka